<a href="https://colab.research.google.com/github/JoyeBright/transformers-course/blob/main/FIVE.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install datasets evaluate transformers[sentencepiece]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [2]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"

tokenizer = AutoTokenizer.from_pretrained(checkpoint)

sentences = ["I've been waiting for a HuggingFace course my whole life,",
                   "I hate this."
                   ]
tokens = [tokenizer.tokenize(sentence) for sentence in sentences]
ids = [tokenizer.convert_tokens_to_ids(token) for token in tokens]

print(ids[0])
print(ids[1])

[1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1010]
[1045, 5223, 2023, 1012]


In [3]:
tokenizer.pad_token_id

0

In [4]:
ids = [[1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1010],
         [1045,  5223, 2023, 1012,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0]
       ]

In [5]:
input_ids = torch.tensor(ids)

In [6]:
input_ids

tensor([[ 1045,  1005,  2310,  2042,  3403,  2005,  1037, 17662, 12172,  2607,
          2026,  2878,  2166,  1010],
        [ 1045,  5223,  2023,  1012,     0,     0,     0,     0,     0,     0,
             0,     0,     0,     0]])

In [7]:
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

In [8]:
id1 = torch.tensor([[1045, 1005, 2310, 2042, 3403, 2005, 1037, 17662, 12172, 2607, 2026, 2878, 2166, 1010]])

In [9]:
id2 = torch.tensor([[1045,  5223, 2023, 1012]])

In [10]:
print(model(id1).logits)
print(model(id2).logits)

tensor([[-3.0963,  3.2720]], grad_fn=<AddmmBackward0>)
tensor([[ 3.9497, -3.1357]], grad_fn=<AddmmBackward0>)


In [12]:
print(model(input_ids).logits)

tensor([[-3.0963,  3.2720],
        [ 1.5444, -1.3998]], grad_fn=<AddmmBackward0>)


In [13]:
attention_mask = [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
         [1,  1, 1, 1,    0,    0,    0,     0,     0,    0,    0,    0,    0,    0]
       ]

In [14]:
attention_mask = torch.tensor(attention_mask)

In [15]:
outputs = model(input_ids, attention_mask = attention_mask)

In [16]:
print(outputs.logits)

tensor([[-3.0963,  3.2720],
        [ 3.9497, -3.1357]], grad_fn=<AddmmBackward0>)
