<a href="https://colab.research.google.com/github/JoyeBright/transformers-course/blob/main/TWO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install datasets evaluate transformers[sentencepiece]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 365 kB 17.4 MB/s 
     |████████████████████████████████| 69 kB 4.8 MB/s 
     |████████████████████████████████| 4.7 MB 37.4 MB/s 
     |████████████████████████████████| 141 kB 58.2 MB/s 
     |████████████████████████████████| 101 kB 3.5 MB/s 
     |████████████████████████████████| 115 kB 39.2 MB/s 
     |████████████████████████████████| 212 kB 41.9 MB/s 
     |████████████████████████████████| 596 kB 48.0 MB/s 
     |████████████████████████████████| 127 kB 53.9 MB/s 
     |████████████████████████████████| 6.6 MB 60.0 MB/s 
     |████████████████████████████████| 1.2 MB 58.9 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3
  Attempting uninstall: pyyaml
    Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
 

In [2]:
from transformers import pipeline

In [3]:
from transformers import AutoTokenizer

In [4]:
checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

In [27]:
raw_inputs = [
    "AI students can expand their understanding in the field by implementing small projects using any programming languages.",
    "The service was sloppy.",
]

In [29]:
inputs = tokenizer(raw_inputs, padding=True, truncation=True, return_tensors="pt")

In [30]:
print(inputs)

{'input_ids': tensor([[  101,  9932,  2493,  2064,  7818,  2037,  4824,  1999,  1996,  2492,
          2011, 14972,  2235,  3934,  2478,  2151,  4730,  4155,  1012,   102],
        [  101,  1996,  2326,  2001, 28810,  1012,   102,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])}


In [31]:
from transformers import AutoModel

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModel.from_pretrained(checkpoint)

Some weights of the model checkpoint at distilbert-base-uncased-finetuned-sst-2-english were not used when initializing DistilBertModel: ['classifier.weight', 'pre_classifier.bias', 'classifier.bias', 'pre_classifier.weight']
- This IS expected if you are initializing DistilBertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing DistilBertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [32]:
outputs = model(**inputs)
print(outputs.last_hidden_state.shape)

torch.Size([2, 20, 768])


In [33]:
outputs[0]

tensor([[[ 0.2816,  0.0761,  0.6599,  ...,  0.0660,  0.3570, -0.2218],
         [ 0.1654,  0.7246,  0.2941,  ..., -0.3425, -0.1139, -0.2492],
         [-0.1266,  0.7333,  0.8087,  ...,  0.1542, -0.0298, -0.6491],
         ...,
         [-0.0381,  0.5042,  0.3492,  ..., -0.9276, -0.1276,  0.2209],
         [ 0.9223, -0.0018,  0.0795,  ...,  0.5936, -0.4388, -0.3338],
         [ 0.8041,  0.1286,  0.2659,  ...,  0.5617, -0.3532, -0.2176]],

        [[-0.7426,  0.2649, -0.0486,  ...,  0.0681, -0.6009, -0.3612],
         [-0.7248,  0.2585, -0.2621,  ...,  0.3333, -0.6573, -0.3010],
         [-0.1497,  0.7680, -0.0212,  ...,  0.0735, -0.4821,  0.0056],
         ...,
         [-0.7119,  0.3286,  0.0588,  ...,  0.1937, -0.5869, -0.2622],
         [-0.6829,  0.2057, -0.0600,  ...,  0.2345, -0.5076, -0.4303],
         [-0.6827,  0.3042,  0.0010,  ...,  0.2774, -0.6052, -0.3376]]],
       grad_fn=<NativeLayerNormBackward0>)

In [34]:
from transformers import AutoModelForSequenceClassification

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
model = AutoModelForSequenceClassification.from_pretrained(checkpoint)

outputs = model(**inputs)

In [35]:
print(outputs.logits.shape)
print(outputs.logits)

torch.Size([2, 2])
tensor([[-2.7738,  2.7945],
        [ 4.4645, -3.6894]], grad_fn=<AddmmBackward0>)


In [36]:
import torch

In [37]:
predictions = torch.nn.functional.softmax(outputs.logits, dim=-1)

In [38]:
print(predictions)

tensor([[3.8024e-03, 9.9620e-01],
        [9.9971e-01, 2.8754e-04]], grad_fn=<SoftmaxBackward0>)


In [39]:
model.config.id2label

{0: 'NEGATIVE', 1: 'POSITIVE'}